---
kind: Service
apiVersion: v1
metadata:
  name: express-service
spec:
  type: LoadBalancer
  selector:
    app: express
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000

